FROM node:22-alpine as build

WORKDIR /frontend

ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}
ENV MODE=development
ENV NODE_ENV=development

COPY package.json yarn.lock .yarnrc.yml postinstall.js .
COPY . .

RUN npm install -g --force yarn
RUN yarn global add vite
RUN yarn --ignore-platform
RUN yarn clean
RUN yarn build

ENV PORT=9997

EXPOSE ${PORT}
