version: "3.9"

services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: dev_postgres
    environment:
      PORT: $POSTGRES_PORT
      BACKEND_PG_HOST: $BACKEND_PG_HOST
      PGADMIN_PG_HOST: $PGADMIN_PG_HOST
    env_file:
      - ./.env
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - dev_network

  vite-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile_dev # Usa el Dockerfile específico para desarrollo
    container_name: vite-dev
    environment:
      PORT: $VITE_DEV_PORT
    env_file:
      - ./.env
    ports:
      - "$VITE_DEV_PORT:$VITE_DEV_PORT"
    volumes:
      - ./frontend:/frontend
    command: sh -c "yarn install && yarn dev --host 0.0.0.0"

  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile_dev
      args:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_DB_URL: ${POSTGRES_DB_URL}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    container_name: dev_backend
    env_file:
      - ./.env
    environment:
      PORT: $BACKEND_PORT
      JAVA_OPTS: -Dspring.devtools.restart.enabled=true -Dspring.devtools.livereload.enabled=true
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "$BACKEND_PORT:$BACKEND_PORT"
    depends_on:
      - postgres
    networks:
      - dev_network
    volumes:
      - ./backend/src:/backend/src # Monta el directorio del código fuente
      - ./backend/.mvn/.m2:/root/.m2
    command: ./reload.sh

  pgadmin:
    build:
      context: ./pgadmin
      dockerfile: Dockerfile
    container_name: dev_pgadmin
    environment:
      PORT: $PGADMIN_PORT
      PGADMIN_LISTEN_PORT: $PGADMIN_LISTEN_PORT
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL # Cambiar según preferencia
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD # Cambiar según preferencia
    ports:
      - "$PGADMIN_PORT:$PGADMIN_PORT"
    depends_on:
      - postgres
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge
volumes:
  postgres_data:
