server:
  port: ${PORT:8080} 
app:
  frontend-url: ${FRONTEND_URL}
  hexadecimal-master-key: ${BACKEND_MASTER_KEY}
  mongo-db: ${MONGO_DB}
  auth-registration-key: ${BACKEND_AUTH_REGISTRATION_KEY}
spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  data:
    mongodb:
      uri: ${MONGO_DB_URL}
      database: ${MONGO_DB}