# Usa la imagen oficial de pgAdmin
FROM dpage/pgadmin4:7.8

# Configuración de variables de entorno
ENV PGADMIN_DEFAULT_EMAIL=asdasdasd@asdasdasdasd.com
ENV PGADMIN_DEFAULT_PASSWORD=asdasdasdasdasdasdasd

# Expone el puerto 80 para el acceso web
EXPOSE 80
