server:
  port: ${PORT}

spring:
  datasource:
    url: ${POSTGRES_DB_URL}
    db: ${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:db/migration
    baselineOnMigrate: true
    baselineVersion: 0
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true